# This is a basic workflow to help you get started with Actions

name: CI Kotlin 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-12

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Java JDK
      - name: Build with gradle
      - uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '17'
          cache: 'gradle'
      - run: ./gradlew build --no-daemon
        
      # Runs a single command using the runners shell
      - name: Build with kotlin compiler
        run: kotlinc src/main/kotlin/Main.kt -include-runtime -d epochtime.jar

      # Runs a set of commands using the runners shell
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: jar-artifact
          path: epochtime.jar
